default: &default
  adapter: postgresql
  encoding: unicode
  username: gaming
  password: <%= ENV['GAMING_DATABASE_PASSWORD'] %>
  pool: 5

production:
  <<: *default
  database: gaming_production
  url: <%= ENV['DATABASE_URL'] %>

development:
  <<: *default
  database: gamIng_development

test:
  <<: *default
  database: gamIng_test
